### PR TITLE
Update for CUDA 12.4.1

### PR DESCRIPTION
**Pull request by adibbley**
xref: https://github.com/conda-forge/cuda-feedstock/issues/23

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by adibbley** [comment]
Requires cuda-cudart to be available.

**Comment by adibbley** [comment]
@conda-forge-admin, please restart ci

**Comment by jakirkham** [comment]
One of the Travis CI builds failed on `main`. Restart [here]( https://app.travis-ci.com/github/conda-forge/libnvjpeg-feedstock/jobs/620205464 )

**Pull request merged**
